### ISSUE TITLE
照你的方法做，报错如下

### ISSUE THREAD

**Issue by harrywu001** [ienaga/RedisPlugin#4]
( ! ) Fatal error: Uncaught Error: Class 'RedisPlugin\Service' not found in D:\wamp64\www\store\app\config\services.php on line 129
--

**Comment by ienaga** [comment]
@harryheng 

你是如何安装的？

建议
`composer install -o --prefer-source --no-interaction`

**Comment by harrywu001** [comment]
@ienaga 能不能不用yaml做配置？

**Comment by ienaga** [comment]
@harryheng 

yaml不是强制性的。
如果你设置DI的配置，它将工作。
这个插件仅支持Phalcon框架。

**Comment by harrywu001** [comment]
@ienaga 你有qq吗？或别的即时通讯工具，方便与你交流

**Comment by ienaga** [comment]
@harryheng 
请在这里联系
EMail: ienaga@tvon.jp

你甚至可以使用github
